In [1]:
from google.colab import files
upload = files.upload()

Saving drug200.csv to drug200.csv


In [58]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [28]:
dataset = pd.read_csv('drug200.csv')
dataset

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [29]:
df = pd.DataFrame(dataset)
df

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [45]:
df.drop(['Age'],axis=1, inplace=True)


In [46]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
df['BP']= label_encoder.fit_transform(df['BP'])

df['BP'].unique()

array([0, 1, 2])

In [47]:
df['Drug']= label_encoder.fit_transform(df['Drug'])

df['Drug'].unique()

array([0, 3, 4, 1, 2])

In [48]:
df['Cholesterol']= label_encoder.fit_transform(df['Cholesterol'])

df['Cholesterol'].unique()

array([0, 1])

In [49]:
df

BP  Cholesterol   Na_to_K  Drug
0     0            0  0.596848     0
1     1            0  0.213397     3
2     1            0  0.120239     3
3     2            0  0.047814     4
4     1            0  0.368191     0
..   ..          ...       ...   ...
195   1            0  0.165676     3
196   1            0  0.179405     3
197   2            0  0.113359     4
198   2            1  0.242385     4
199   1            1  0.158859     4

[200 rows x 4 columns]

In [50]:
dataset.shape

(200, 6)

In [51]:
def min_max_normallize(dataset):
    min_val = np.min(dataset, axis=0)
    max_val = np.max(dataset, axis=0)
    normal = (dataset - min_val) / (max_val - min_val)
    return normal

In [52]:
df = min_max_normallize(df)
df

BP  Cholesterol   Na_to_K  Drug
0    0.0          0.0  0.596848  0.00
1    0.5          0.0  0.213397  0.75
2    0.5          0.0  0.120239  0.75
3    1.0          0.0  0.047814  1.00
4    0.5          0.0  0.368191  0.00
..   ...          ...       ...   ...
195  0.5          0.0  0.165676  0.75
196  0.5          0.0  0.179405  0.75
197  1.0          0.0  0.113359  1.00
198  1.0          1.0  0.242385  1.00
199  0.5          1.0  0.158859  1.00

[200 rows x 4 columns]

In [53]:
x = df.iloc[:, :5]
y = df.iloc[:, 0]
x

BP  Cholesterol   Na_to_K  Drug
0    0.0          0.0  0.596848  0.00
1    0.5          0.0  0.213397  0.75
2    0.5          0.0  0.120239  0.75
3    1.0          0.0  0.047814  1.00
4    0.5          0.0  0.368191  0.00
..   ...          ...       ...   ...
195  0.5          0.0  0.165676  0.75
196  0.5          0.0  0.179405  0.75
197  1.0          0.0  0.113359  1.00
198  1.0          1.0  0.242385  1.00
199  0.5          1.0  0.158859  1.00

[200 rows x 4 columns]

In [54]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [55]:
model = LinearRegression()
model.fit(x_train, y_train)


LinearRegression()

In [56]:
y_pred = model.predict(x_test)

In [59]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print('MSE=', mse)
print('R2=', r2)


MSE= 7.248997966571889e-32
R2= 1.0


In [60]:
model.coef_

array([ 1.00000000e+00,  3.05880261e-16, -8.27640606e-17, -3.00743473e-16])

In [61]:
model.intercept_

1.1102230246251565e-16

In [62]:
from sklearn.preprocessing import PolynomialFeatures

In [63]:
poly_reg = PolynomialFeatures(degree=8)
x_poly = poly_reg.fit_transform(x_test)
model.fit(x_poly, y_test)


LinearRegression()

In [64]:
y_pred = model.predict(x_poly)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print('MSE=', mse)
print('R2=', r2)


MSE= 6.521795838598232e-30
R2= 1.0
